"""Chapters 36-40 for the PokeTech Arcana quest book."""

CHAPTERS = {
    "starlight": {
        "title": "Eternal Starlight: сердце измерения", "file": "starlight",
        "icon": "eternal_starlight:aethersent_ingot", "target_count": 90, "append_control": False,
        "stages": [
            ("I · ПОРТАЛ", "Врата к звёздам", ["След измерения", "Подготовка экспедиции", "Портальная площадка", "Активация врат", "Первый переход", "Точка возврата", "Защитный комплект", "Полевой сундук", "Безопасный маршрут", "Звёздный разведчик"]),
            ("II · ЛАГЕРЬ", "Первый лагерь", ["Выбор места", "Источник света", "Запас пищи", "Склад образцов", "Укрытие", "Навигационный знак", "Аварийный комплект", "Ночная смена", "Связь с базой", "Экспедиционный лагерь"]),
            ("III · БИОМЫ", "Карта чужого неба", ["Лунный лес", "Кристальная долина", "Пепельные поля", "Бездонные глубины", "Редкая растительность", "Опасная зона", "Высотный маршрут", "Карта биомов", "Коллекция образцов", "Знаток Starlight"]),
            ("IV · РЕСУРСЫ", "Звёздные материалы", ["Abysslate", "Starlight Crystal", "Amaramber", "Aethersent", "Необычная древесина", "Сплав измерения", "Обработка кристалла", "Хранилище ресурсов", "Редкий образец", "Звёздный металлург"]),
            ("V · РЕМЕСЛО", "Мастерская измерения", ["Alloy Furnace", "Кристальный свет", "Новые инструменты", "Защитная броня", "Дальнее оружие", "Полевой прибор", "Усиление снаряжения", "Полный комплект", "Испытание комплекта", "Мастер звёздного ремесла"]),
            ("VI · РУИНЫ", "Археология Starlight", ["След руин", "Вход в комплекс", "Ловушки", "Первая реликвия", "Закрытая камера", "Ключевой предмет", "Архив находок", "Глубинный зал", "Безопасный вынос", "Хранитель руин"]),
            ("VII · СУЩЕСТВА", "Жизнь измерения", ["Мирное существо", "Хищник", "Воздушный вид", "Подземный вид", "Следы поведения", "Безопасное наблюдение", "Материал существа", "Атлас фауны", "Редкий вид", "Натуралист Starlight"]),
            ("VIII · СТРАЖИ", "Испытания хранителей", ["Подготовка арены", "Первый страж", "Механика атаки", "Защитная фаза", "Командная роль", "Трофей стража", "Второй вызов", "Серия побед", "Главный хранитель", "Покоритель измерения"]),
            ("IX · СЕРДЦЕ", "Сердце измерения", ["Четыре ключа", "Звёздный алтарь", "Стабилизация портала", "Сердце кристалла", "Финальный маршрут", "Последнее испытание", "Источник силы", "Монумент экспедиции", "Возвращение домой", "Наследие Starlight"]),
        ],
        "centers": [(8, 24), (25, 8), (47, 6), (70, 10), (91, 24), (73, 40), (47, 43), (24, 39), (50, 24)],
        "patterns": ["fanR", "ring", "diamond", "grid", "crescentL", "containment", "star", "doubleRing", "ritual"],
    },
    "wildlife": {
        "title": "Живая природа: большой атлас", "file": "wildlife", "icon": "minecraft:spyglass",
        "target_count": 80, "append_control": False,
        "stages": [
            ("I · СТАНЦИЯ", "Полевая станция", ["Бинокль", "Дневник", "Компас", "Палатка", "Кормушка", "Фото-точка", "Контейнер образцов", "Аптечка", "Правила наблюдения", "Станция готова"]),
            ("II · ЛЕС", "Лесной маршрут", ["Следы животных", "Птицы кроны", "Ночной обитатель", "Гнездо", "Редкое растение", "Безопасная тропа", "Кормовая точка", "Лесной образец", "Каталог леса", "Хранитель леса"]),
            ("III · РЕКА", "Речная экосистема", ["Берег", "Рыба", "Амфибия", "Водное растение", "Чистая вода", "Мост наблюдения", "Ночная съёмка", "Речной образец", "Каталог реки", "Исследователь рек"]),
            ("IV · БОЛОТО", "Тихая топь", ["Топкая тропа", "Лягушки", "Насекомые", "Грибы", "Редкий цветок", "Защитная одежда", "Проба воды", "Ночная экспедиция", "Каталог болота", "Знаток топей"]),
            ("V · ОКЕАН", "Морская экспедиция", ["Лодка", "Компас моря", "Кораллы", "Тропическая рыба", "Глубинный вид", "Подводный свет", "Безопасное погружение", "Морской образец", "Каталог океана", "Океанолог"]),
            ("VI · РЕДКОСТИ", "Редкие виды", ["Редкий след", "Тихое приближение", "Особый биом", "Погодное условие", "Редкая окраска", "Наблюдение без вреда", "Полевая запись", "Подтверждение находки", "Заповедная зона", "Открытие года"]),
            ("VII · БЕЗОПАСНОСТЬ", "Этика исследователя", ["Дистанция", "Не кормить хищников", "Чистый лагерь", "Защита гнезда", "Возврат существа", "Помощь раненому", "Маршрут без вреда", "Знак заповедника", "Обучение команды", "Ответственный натуралист"]),
            ("VIII · АТЛАС", "Большой атлас", ["Лесной раздел", "Речной раздел", "Болотный раздел", "Океанский раздел", "Ночные виды", "Редкие виды", "Карта наблюдений", "Архив образцов", "Выставка атласа", "Главный натуралист"]),
        ],
        "centers": [(10, 24), (30, 8), (52, 8), (74, 18), (73, 39), (50, 43), (28, 39), (49, 24)],
        "patterns": ["grid", "crescentR", "ring", "fanL", "diamond", "star", "mirror", "doubleRing"],
    },
    "arsplus": {
        "title": "Ars Nouveau+: школы стихий", "file": "arsplus", "icon": "ars_nouveau:archmage_spell_book",
        "target_count": 90, "append_control": False,
        "stages": [
            ("I · ЯДРО", "Ядро магии", ["Книга архимага", "Источник", "Письменный стол", "Базовая форма", "Первый эффект", "Усилитель", "Безопасное заклинание", "Свиток", "Проверка маны", "Ядро готово"]),
            ("II · ОГОНЬ", "Школа огня", ["Искра", "Поджог", "Огненный снаряд", "Взрыв", "Пламенная стена", "Сопротивление огню", "Усиление", "Огненная турель", "Комбинация огня", "Маг огня"]),
            ("III · ВОДА", "Вода и лёд", ["Поток", "Заморозка", "Ледяной снаряд", "Водное дыхание", "Скользящий путь", "Ледяная стена", "Контроль зоны", "Ледяная турель", "Комбинация воды", "Маг льда"]),
            ("IV · ВОЗДУХ", "Школа воздуха", ["Порыв", "Прыжок", "Мягкое падение", "Ускорение", "Отталкивание", "Полёт", "Воздушный щит", "Дальняя форма", "Комбинация воздуха", "Маг воздуха"]),
            ("V · ЗЕМЛЯ", "Школа земли", ["Разрушение", "Поднятие блока", "Каменная стена", "Рост", "Корни", "Урожай", "Защитный круг", "Рабочая турель", "Комбинация земли", "Маг земли"]),
            ("VI · CREO", "Ars Creo", ["Кинетический мост", "Источник движения", "Магическая передача", "Ритуальный привод", "Автосбор", "Механический помощник", "Контроль потока", "Гибридная машина", "Автолиния", "Инженер Creo"]),
            ("VII · OCULTAS", "Ars Ocultas", ["Тайный глиф", "Сокрытие", "Обнаружение", "Печать", "Ловушка", "Защитный оберег", "Скрытый проход", "Ритуал тайны", "Тайный комплекс", "Мастер Ocultas"]),
            ("VIII · СОСТАВ", "Составные заклинания", ["Три эффекта", "Пять эффектов", "Отложенный эффект", "Цепная цель", "Большая область", "Экономия маны", "Боевой состав", "Рабочий состав", "Мобильный состав", "Конструктор заклинаний"]),
            ("IX · АРХИМАГ", "Архимаг интеграций", ["Магическая ферма", "Магический склад", "Магическая защита", "Портальная сеть", "Фамильяры", "Автоматические ритуалы", "Связь с технологиями", "Полный гримуар", "Испытание архимага", "Великий архимаг"]),
        ],
        "centers": [(50, 23), (25, 4), (50, 4), (75, 4), (92, 23), (76, 42), (50, 44), (24, 41), (8, 23)],
        "patterns": ["ritual", "star", "crescentD", "fanL", "diamond", "grid", "containment", "doubleRing", "ring"],
    },
    "mekplus": {
        "title": "Mekanism+: энергетический комплекс", "file": "mekplus", "icon": "mekanismgenerators:wind_generator",
        "target_count": 100, "append_control": False,
        "stages": [
            ("I · ШИНА", "Энергетическая шина", ["Universal Cable", "Energy Cube", "Контроль сети", "Потери", "Буфер", "Приоритет", "Резерв", "Аварийная линия", "Мониторинг", "Шина готова"]),
            ("II · ТЕПЛО", "Тепловая энергия", ["Heat Generator", "Топливо", "Пассивное тепло", "Активный режим", "Буфер энергии", "Охлаждение", "Два генератора", "Стабильная нагрузка", "Тест суток", "Тепловая станция"]),
            ("III · ВЕТЕР", "Ветропарк", ["Wind Generator", "Высота", "Кабельный спуск", "Обслуживание", "Защита", "Три турбины", "Буфер", "Приоритет ветра", "Суточный тест", "Ветропарк"]),
            ("IV · СОЛНЦЕ", "Солнечная станция", ["Solar Generator", "Advanced Solar", "Открытое небо", "Дневной буфер", "Ночной резерв", "Массив панелей", "Контроллер", "Гибридная сеть", "Суточный тест", "Солнечная станция"]),
            ("V · ГАЗ", "Газовая генерация", ["Bio Fuel", "Ethylene", "Gas-Burning Generator", "PRC", "Субстрат", "Трубопровод", "Буфер газа", "Автоподача", "Стабильная выработка", "Газовая станция"]),
            ("VI · ТУРБИНА", "Промышленная турбина", ["Turbine Casing", "Rotor", "Blade", "Rotational Complex", "Electromagnetic Coil", "Condenser", "Valve", "Полная конструкция", "Пуск турбины", "Турбинный зал"]),
            ("VII · FISSION", "Реактор деления", ["Reactor Casing", "Fuel Assembly", "Control Rod", "Reactor Port", "Топливная линия", "Охлаждение", "Ядерные отходы", "SCRAM", "Стабильный цикл", "Fission Reactor"]),
            ("VIII · FUSION", "Термоядерный реактор", ["Reactor Frame", "Controller", "Laser Focus", "D-T Fuel", "Hohlraum", "Лазерный импульс", "Запуск плазмы", "Удержание реакции", "Энергосъём", "Fusion Reactor"]),
            ("IX · TOOLS", "Инструменты и броня", ["Osmium Tool", "Refined Glowstone", "Refined Obsidian", "Paxel", "Полный комплект", "Модульный инструмент", "Зарядка", "Полевой тест", "Защитный тест", "Инженерный комплект"]),
            ("X · КОМПЛЕКС", "Защищённый энергокомплекс", ["Резервная сеть", "Автоматический SCRAM", "Дублирование охлаждения", "Изоляция отходов", "Система доступа", "Центральный контроль", "Пиковая нагрузка", "Суточное испытание", "Монумент энергии", "Главный энергетик"]),
        ],
        "centers": [(7, 23), (24, 8), (46, 5), (68, 8), (90, 22), (82, 42), (58, 45), (34, 43), (15, 36), (50, 24)],
        "patterns": ["fanR", "ring", "grid", "diamond", "crescentL", "mirror", "containment", "star", "doubleRing", "ritual"],
    },
    "community": {
        "title": "Сообщество: общий проект", "file": "community", "icon": "minecraft:bell",
        "target_count": 80, "append_control": False,
        "stages": [
            ("I · КОМАНДА", "Основание команды", ["Создать команду", "Название", "Эмблема", "Приглашение", "Правила", "Роли", "Общий чат", "Точка встречи", "Первое собрание", "Команда основана"]),
            ("II · БАЗА", "Общая база", ["Выбор участка", "План базы", "Склад", "Мастерская", "Жилая зона", "Освещение", "Навигация", "Безопасность", "Гостевая зона", "Штаб готов"]),
            ("III · РОЛИ", "Распределение ролей", ["Инженер", "Маг", "Фермер", "Исследователь", "Тренер", "Строитель", "Снабженец", "Заместитель", "Смена роли", "Слаженная команда"]),
            ("IV · РЕСУРСЫ", "Общие ресурсы", ["Общий сундук", "Правила выдачи", "Минимальный запас", "Редкие ресурсы", "Автосортировка", "Заказ ресурсов", "Аварийный резерв", "Учёт", "Пополнение", "Общий склад"]),
            ("V · ТЕРРИТОРИЯ", "Развитие территории", ["Карта зоны", "Дорога", "Портал", "Ферма", "Энергостанция", "Покецентр", "Арена", "Парк", "Освещение", "Развитый район"]),
            ("VI · КОНТРАКТЫ", "Командные контракты", ["Первый заказ", "Ресурсный контракт", "Строительный контракт", "Экспедиционный контракт", "Боевой контракт", "Срочный заказ", "Редкая награда", "Серия заказов", "Репутация", "Гильдейский подряд"]),
            ("VII · ЭКСПЕДИЦИИ", "Совместные экспедиции", ["Маршрут", "Состав группы", "Снабжение", "Распределение ролей", "Точка эвакуации", "Данж", "Босс", "Вынос трофеев", "Отчёт", "Экспедиционный корпус"]),
            ("VIII · ПРОЕКТ", "Проект сервера", ["Выбор мегапроекта", "Сбор материалов", "Фундамент", "Технологический узел", "Магический узел", "Покемонский узел", "Общая сборка", "Испытание", "Открытие", "Наследие сообщества"]),
        ],
        "centers": [(10, 24), (30, 7), (55, 5), (80, 12), (91, 32), (67, 43), (40, 43), (51, 24)],
        "patterns": ["doubleRing", "grid", "fanL", "ring", "diamond", "crescentD", "star", "containment"],
    },
}

ITEM_POOLS = {
    "starlight": [
        "eternal_starlight:abyssal_fruit", "eternal_starlight:abysslate", "eternal_starlight:aethersent_ingot",
        "eternal_starlight:aethersent_nugget", "eternal_starlight:alloy_furnace", "eternal_starlight:amaramber_ingot",
        "eternal_starlight:amaramber_bricks", "eternal_starlight:amaramber_lantern", "eternal_starlight:amaramber_pickaxe",
        "eternal_starlight:amaramber_sword", "eternal_starlight:ashen_snow", "eternal_starlight:aurora_deer_antler",
        "eternal_starlight:banyin_log", "eternal_starlight:banyin_planks", "eternal_starlight:blaze_crystal",
        "eternal_starlight:blue_starlight_crystal_block", "eternal_starlight:blue_starlight_crystal_shard",
        "eternal_starlight:blossom_of_stars", "eternal_starlight:aureate_flower", "eternal_starlight:blue_crystalfleur"
    ],
    "wildlife": ["minecraft:spyglass", "minecraft:writable_book", "minecraft:compass", "minecraft:map", "minecraft:lead", "minecraft:name_tag", "minecraft:oak_sapling", "minecraft:lily_pad", "minecraft:kelp", "minecraft:seagrass", "minecraft:tropical_fish", "minecraft:salmon", "minecraft:cod", "minecraft:pufferfish", "minecraft:honey_bottle", "minecraft:glow_berries", "minecraft:slime_ball", "minecraft:feather", "minecraft:rabbit_hide", "minecraft:turtle_scute"],
    "arsplus": ["ars_nouveau:archmage_spell_book", "ars_nouveau:source_jar", "ars_nouveau:sourcestone", "ars_nouveau:scribes_table", "ars_nouveau:blank_glyph", "ars_nouveau:glyph_touch", "ars_nouveau:glyph_projectile", "ars_nouveau:glyph_break", "ars_nouveau:glyph_amplify", "ars_nouveau:glyph_aoe", "ars_nouveau:glyph_pierce", "ars_nouveau:glyph_delay", "ars_nouveau:glyph_extend_time", "ars_nouveau:glyph_harvest", "ars_nouveau:spell_turret", "ars_nouveau:spell_prism", "ars_nouveau:source_gem_block", "ars_nouveau:ritual_brazier", "ars_nouveau:dominion_wand", "ars_nouveau:stable_warp_scroll"],
    "mekplus": ["mekanism:advanced_universal_cable", "mekanism:advanced_energy_cube", "mekanismgenerators:heat_generator", "mekanismgenerators:wind_generator", "mekanismgenerators:solar_generator", "mekanismgenerators:advanced_solar_generator", "mekanismgenerators:gas_burning_generator", "mekanism:bio_fuel", "mekanism:pressurized_reaction_chamber", "mekanismgenerators:turbine_casing", "mekanismgenerators:turbine_valve", "mekanismgenerators:turbine_rotor", "mekanismgenerators:rotational_complex", "mekanismgenerators:electromagnetic_coil", "mekanismgenerators:saturating_condenser", "mekanismgenerators:fission_reactor_casing", "mekanismgenerators:fission_reactor_port", "mekanismgenerators:fission_fuel_assembly", "mekanismgenerators:control_rod_assembly", "mekanismgenerators:fusion_reactor_frame", "mekanismgenerators:fusion_reactor_controller", "mekanismgenerators:laser_focus_matrix", "mekanism:hazmat_mask", "mekanism:radioactive_waste_barrel"],
    "community": ["minecraft:bell", "minecraft:book", "minecraft:map", "minecraft:compass", "minecraft:chest", "minecraft:barrel", "minecraft:lantern", "minecraft:lodestone", "minecraft:white_banner", "minecraft:lectern", "minecraft:crafting_table", "minecraft:anvil", "minecraft:ender_chest", "minecraft:beacon", "minecraft:nether_star", "minecraft:dragon_egg", "minecraft:emerald", "minecraft:diamond", "minecraft:gold_ingot", "minecraft:clock"],
}
