"""Quest data for the Immersive Engineering learning chapter."""


def n(key, title, phase, desc, px, py, shape, size, task, deps, reward, xp, tag, icon=None):
    x = round((px - 80) * 0.03, 2)
    y = round((py - 580) * 0.03, 2)
    tasks = task if isinstance(task, tuple) and task and isinstance(task[0], tuple) else (task,)
    return key, title, phase, desc, x, y, shape, size, tuple(tasks), tuple(deps), reward, xp, tag, icon


NODES = [
    # Main path.
    n("manual", "Руководство инженера", "I · РУКОВОДСТВО", "Создай Engineer's Manual и научись читать схемы многоблочных машин.", 80, 580, "diamond", 1.6, ("immersiveengineering:manual", 1), (), ("immersiveengineering:hammer", 1), 2, "pta_main"),
    n("hammer", "Молот инженера", "I · РУКОВОДСТВО", "Освой главный инструмент: поворот блоков, формирование многоблоков и диагностика.", 225, 600, "circle", 1.15, ("immersiveengineering:hammer", 1), ("manual",), ("immersiveengineering:wirecutter", 1), 2, "pta_main"),
    n("cokebrick", "Коксовые кирпичи", "II · МАТЕРИАЛЫ", "Подготовь полный комплект кирпичей и свободный куб 3×3×3.", 370, 580, "circle", 1.15, ("immersiveengineering:cokebrick", 27), ("hammer",), ("minecraft:coal", 16), 3, "pta_main"),
    n("cokeoven", "Коксовая печь", "II · МАТЕРИАЛЫ", "Собери первую многоблочную машину и проверь её работой, получив кокс и креозот.", 515, 600, "hexagon", 1.4, (("immersiveengineering:coal_coke", 16), ("immersiveengineering:creosote_bucket", 1)), ("cokebrick", "constantan"), ("immersiveengineering:treated_wood_horizontal", 16), 4, "pta_main", "immersiveengineering:coke_oven"),
    n("blastbrick", "Доменные кирпичи", "III · СТАЛЬ", "Подготовь жаростойкий корпус для первого производства стали.", 660, 580, "circle", 1.15, ("immersiveengineering:blastbrick", 27), ("cokeoven",), ("immersiveengineering:coal_coke", 16), 4, "pta_main"),
    n("blastfurnace", "Доменная печь", "III · СТАЛЬ", "Переплавь железо с коксовым углём и получи первую сталь.", 805, 600, "hexagon", 1.4, ("immersiveengineering:ingot_steel", 8), ("blastbrick",), ("immersiveengineering:plate_steel", 4), 5, "pta_main", "immersiveengineering:blast_furnace"),
    n("workbench", "Верстак инженера", "III · СТАЛЬ", "Собирай компоненты, улучшения и оборудование по чертежам.", 950, 580, "square", 1.35, ("immersiveengineering:workbench", 1), ("blastfurnace", "steel_flow"), ("immersiveengineering:blueprint", 1), 5, "pta_main"),
    n("lv_network", "Сеть низкого напряжения", "IV · ЭНЕРГИЯ LV", "Построй безопасную LV-сеть с генератором, накопителем и потребителем.", 1095, 600, "hexagon", 1.4, (("immersiveengineering:capacitor_lv", 1), ("immersiveengineering:connector_lv", 2), ("immersiveengineering:wirecoil_copper", 4)), ("workbench",), ("immersiveengineering:voltmeter", 1), 6, "pta_main", "immersiveengineering:capacitor_lv"),
    n("metal_press", "Металлический пресс", "VI · МАШИНЫ", "Автоматизируй пластины, стержни, проволоку и механические компоненты.", 1240, 580, "square", 1.45, ("immersiveengineering:metal_press", 1), ("lv_network", "charging_station"), ("immersiveengineering:mold_plate", 1), 7, "pta_main"),
    n("crusher", "Дробитель", "VI · МАШИНЫ", "Удвой руду и организуй безопасный вывод продукции конвейерами.", 1385, 600, "square", 1.45, ("immersiveengineering:crusher", 1), ("metal_press",), ("immersiveengineering:conveyor_basic", 8), 8, "pta_main"),
    n("fluid_network", "Насос и резервуар", "VII · ТОПЛИВО", "Научись перекачивать, хранить и фильтровать промышленные жидкости.", 1530, 580, "circle", 1.25, (("immersiveengineering:fluid_pump", 1), ("immersiveengineering:tank", 1)), ("crusher", "current_transformer"), ("immersiveengineering:fluid_pipe", 8), 7, "pta_main"),
    n("refinery", "Нефтепереработка", "VII · ТОПЛИВО", "Соедини ферментер, выжимной пресс и нефтеперерабатывающий завод.", 1675, 600, "square", 1.45, ("immersiveengineering:refinery", 1), ("fluid_network",), ("immersiveengineering:biodiesel_bucket", 1), 9, "pta_main"),
    n("biodiesel", "Биодизель", "VII · ТОПЛИВО", "Получай растительное масло и этанол, затем смешивай их в стабильное топливо.", 1820, 580, "circle", 1.3, ("immersiveengineering:biodiesel_bucket", 4), ("refinery", "auto_line"), ("immersiveengineering:high_power_biodiesel_bucket", 1), 9, "pta_main"),
    n("diesel_generator", "Дизельный генератор", "VII · ТОПЛИВО", "Переведи биодизель в серьёзный поток FE и измерь реальную нагрузку.", 1965, 600, "square", 1.5, ("immersiveengineering:diesel_generator", 1), ("biodiesel", "generator_load"), ("immersiveengineering:capacitor_hv", 1), 11, "pta_main"),
    n("arc_furnace", "Дуговая печь", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Освой электроды, легирование, переработку и массовую плавку.", 2110, 580, "square", 1.55, (("immersiveengineering:arc_furnace", 1), ("immersiveengineering:graphite_electrode", 3)), ("diesel_generator",), ("immersiveengineering:plate_hop_graphite", 4), 13, "pta_transition"),
    n("industrial_complex", "Промышленный комплекс", "IX · ИНТЕГРАЦИЯ", "Объедини энергию, переработку, топливо и тяжёлые машины; подготовь стабильный выход ресурсов для Mekanism.", 2290, 600, "diamond", 1.85, (("immersiveengineering:storage_steel", 16), ("immersiveengineering:capacitor_hv", 2), ("immersiveengineering:reinforced_crate", 4)), ("arc_furnace", "arc_recycling", "turret"), ("mekanism:ingot_osmium", 16), 18, "pta_transition"),

    # Materials branch.
    n("hemp", "Промышленная конопля", "II · МАТЕРИАЛЫ", "Получи семена, вырасти коноплю и собери первое волокно для ткани и проводов.", 125, 420, "octagon", 1.0, (("immersiveengineering:seed", 1), ("immersiveengineering:hemp_fiber", 32)), ("manual",), ("immersiveengineering:hemp_fiber", 16), 2, "pta_resource"),
    n("hemp_fiber", "Волокно", "II · МАТЕРИАЛЫ", "Переработай урожай в промышленное волокно.", 170, 330, "octagon", 1.0, ("immersiveengineering:hemp_fiber", 32), ("hemp",), ("immersiveengineering:hemp_fabric", 4), 2, "pta_resource"),
    n("hemp_fabric", "Ткань", "II · МАТЕРИАЛЫ", "Создай ткань для конвейеров, воздушных шаров и оборудования.", 220, 245, "octagon", 1.0, ("immersiveengineering:hemp_fabric", 8), ("hemp_fiber",), ("immersiveengineering:conveyor_basic", 4), 3, "pta_resource"),
    n("creosote", "Креозот", "II · МАТЕРИАЛЫ", "Запланируй безопасное хранение побочной жидкости коксовой печи.", 275, 180, "octagon", 1.0, ("immersiveengineering:creosote_bucket", 4), ("hemp_fabric",), ("minecraft:bucket", 4), 3, "pta_resource"),
    n("treated_wood", "Обработанное дерево", "II · МАТЕРИАЛЫ", "Пропитай доски креозотом — это основа опор и машин.", 330, 145, "octagon", 1.0, ("immersiveengineering:treated_wood_horizontal", 32), ("creosote",), ("immersiveengineering:stick_treated", 16), 3, "pta_resource"),
    n("construction", "Строительные блоки", "II · МАТЕРИАЛЫ", "Освой леса, заборы и инженерные опоры.", 390, 165, "octagon", 1.0, (("immersiveengineering:treated_scaffold", 16), ("immersiveengineering:treated_post", 4)), ("treated_wood",), ("immersiveengineering:treated_fence", 8), 3, "pta_resource"),
    n("alloy_kiln", "Сплавная печь", "II · МАТЕРИАЛЫ", "Собери Alloy Kiln для ранних сплавов без электричества.", 440, 220, "octagon", 1.05, ("immersiveengineering:alloybrick", 8), ("construction",), ("minecraft:copper_ingot", 8), 4, "pta_resource"),
    n("electrum", "Электрум", "II · МАТЕРИАЛЫ", "Соедини золото и серебро для проводников и компонентов.", 475, 300, "octagon", 1.0, ("immersiveengineering:ingot_electrum", 16), ("alloy_kiln",), ("immersiveengineering:wire_electrum", 8), 4, "pta_resource"),
    n("constantan", "Константан", "II · МАТЕРИАЛЫ", "Создай жаростойкий сплав меди и никеля.", 500, 415, "octagon", 1.0, ("immersiveengineering:ingot_constantan", 16), ("electrum",), ("immersiveengineering:plate_constantan", 8), 4, "pta_resource"),

    # Steel branch.
    n("coal_coke", "Коксовый уголь", "III · СТАЛЬ", "Получи эффективное топливо и накопи запас для стали.", 565, 760, "octagon", 1.0, ("immersiveengineering:coal_coke", 32), ("cokeoven",), ("immersiveengineering:coke", 1), 3, "pta_resource"),
    n("creosote_storage", "Креозотовое масло", "III · СТАЛЬ", "Выведи жидкость из печи в отдельный резервуар.", 620, 845, "octagon", 1.0, ("immersiveengineering:creosote_bucket", 8), ("coal_coke",), ("immersiveengineering:tank", 1), 4, "pta_resource"),
    n("first_steel", "Первая сталь", "III · СТАЛЬ", "Выплавь слитки стали и проверь расход кокса.", 690, 920, "octagon", 1.0, ("immersiveengineering:ingot_steel", 16), ("creosote_storage",), ("immersiveengineering:component_steel", 4), 4, "pta_resource"),
    n("steel_components", "Стальные компоненты", "III · СТАЛЬ", "Сделай пластины, стержни, леса и механические детали.", 765, 965, "octagon", 1.0, (("immersiveengineering:plate_steel", 16), ("immersiveengineering:component_steel", 8)), ("first_steel",), ("immersiveengineering:steel_scaffolding_standard", 16), 5, "pta_resource"),
    n("advanced_blast", "Улучшенная домна", "III · СТАЛЬ", "Построй усиленную печь для непрерывной загрузки.", 835, 925, "octagon", 1.05, ("immersiveengineering:blastbrick_reinforced", 27), ("steel_components",), ("immersiveengineering:advanced_blast_furnace", 1), 6, "pta_resource"),
    n("preheaters", "Преднагреватели", "III · СТАЛЬ", "Ускорь выплавку двумя внешними нагревателями.", 890, 850, "octagon", 1.0, ("immersiveengineering:blastfurnace_preheater", 2), ("advanced_blast",), ("immersiveengineering:ingot_steel", 16), 6, "pta_auto"),
    n("steel_flow", "Поток стали", "III · СТАЛЬ", "Автоматизируй вход железа, кокса и выход стали со шлаком.", 930, 760, "octagon", 1.05, (("immersiveengineering:ingot_steel", 64), ("immersiveengineering:slag", 16)), ("preheaters",), ("immersiveengineering:storage_steel", 2), 7, "pta_auto"),

    # LV generation branch.
    n("watermill", "Водяное колесо", "IV · ЭНЕРГИЯ LV", "Создай предсказуемую раннюю генерацию и подбери направление потока.", 840, 430, "circle", 1.0, ("immersiveengineering:watermill", 1), ("blastfurnace",), ("immersiveengineering:dynamo", 1), 4, "pta_auto"),
    n("windmill", "Ветряк", "IV · ЭНЕРГИЯ LV", "Собери альтернативный источник энергии и сравни условия работы.", 890, 340, "circle", 1.0, ("immersiveengineering:windmill", 1), ("watermill",), ("immersiveengineering:windmill_sail", 8), 4, "pta_auto"),
    n("dynamo", "Кинетическое динамо", "IV · ЭНЕРГИЯ LV", "Преобразуй вращение колеса или ветряка в FE.", 945, 260, "circle", 1.0, ("immersiveengineering:dynamo", 1), ("windmill",), ("immersiveengineering:wirecoil_copper", 2), 4, "pta_auto"),
    n("lv_capacitor", "LV-конденсатор", "IV · ЭНЕРГИЯ LV", "Сохраняй избыток энергии и настрой стороны ввода и вывода.", 1005, 200, "circle", 1.0, ("immersiveengineering:capacitor_lv", 1), ("dynamo",), ("immersiveengineering:component_iron", 4), 5, "pta_auto"),
    n("lv_connector", "Разъём LV", "IV · ЭНЕРГИЯ LV", "Подключи генератор и накопитель медным проводом.", 1070, 165, "circle", 1.0, (("immersiveengineering:connector_lv", 4), ("immersiveengineering:wirecoil_copper", 4)), ("lv_capacitor",), ("immersiveengineering:connector_lv_relay", 4), 5, "pta_auto"),
    n("lv_relay", "Реле LV", "IV · ЭНЕРГИЯ LV", "Проводи линию через опоры без подключения к каждому блоку.", 1135, 195, "circle", 1.0, ("immersiveengineering:connector_lv_relay", 8), ("lv_connector",), ("immersiveengineering:treated_post", 4), 5, "pta_auto"),
    n("voltmeter", "Вольтметр", "IV · ЭНЕРГИЯ LV", "Измеряй поток энергии и находи перегруженные участки.", 1185, 260, "circle", 1.0, ("immersiveengineering:voltmeter", 1), ("lv_relay",), ("immersiveengineering:wirecoil_copper_ins", 2), 5, "pta_auto"),
    n("furnace_heater", "Внешний нагреватель", "IV · ЭНЕРГИЯ LV", "Питай обычную печь электричеством и автоматизируй переплавку.", 1215, 340, "circle", 1.0, ("immersiveengineering:furnace_heater", 1), ("voltmeter",), ("minecraft:furnace", 2), 5, "pta_auto"),
    n("charging_station", "Зарядная станция", "IV · ЭНЕРГИЯ LV", "Заряжай инструменты и подготовь сеть к промышленным машинам.", 1225, 430, "circle", 1.05, ("immersiveengineering:charging_station", 1), ("furnace_heater",), ("immersiveengineering:capacitor_lv", 1), 6, "pta_auto"),

    # Wiring and control branch.
    n("wirecutter", "Кусачки", "V · ЭЛЕКТРОСЕТЬ", "Режь провода, возвращай соединения и обслуживай сеть безопасно.", 1130, 760, "circle", 1.0, ("immersiveengineering:wirecutter", 1), ("lv_network",), ("immersiveengineering:wirecoil_copper", 2), 3, "pta_resource"),
    n("copper_wire", "Медный провод", "V · ЭЛЕКТРОСЕТЬ", "Рассчитай длину линии и потери на расстоянии.", 1180, 850, "circle", 1.0, ("immersiveengineering:wirecoil_copper", 8), ("wirecutter",), ("immersiveengineering:wire_copper", 16), 4, "pta_resource"),
    n("insulated_wire", "Изолированный провод", "V · ЭЛЕКТРОСЕТЬ", "Защити рабочую зону от случайного контакта с проводами.", 1240, 930, "circle", 1.0, ("immersiveengineering:wirecoil_copper_ins", 8), ("copper_wire",), ("immersiveengineering:hemp_fabric", 4), 4, "pta_resource"),
    n("transformer", "Трансформатор", "V · ЭЛЕКТРОСЕТЬ", "Преобразуй напряжение между LV и MV без сгорания оборудования.", 1305, 985, "circle", 1.0, ("immersiveengineering:transformer", 1), ("insulated_wire",), ("immersiveengineering:connector_mv", 2), 5, "pta_resource"),
    n("mv_network", "Сеть MV", "V · ЭЛЕКТРОСЕТЬ", "Построй отдельный контур среднего напряжения для крупных машин.", 1370, 1010, "circle", 1.05, (("immersiveengineering:connector_mv", 4), ("immersiveengineering:wirecoil_electrum", 8)), ("transformer",), ("immersiveengineering:connector_mv_relay", 4), 6, "pta_resource"),
    n("mv_capacitor", "MV-конденсатор", "V · ЭЛЕКТРОСЕТЬ", "Буферизуй пики потребления дробителя и пресса.", 1435, 985, "circle", 1.0, ("immersiveengineering:capacitor_mv", 1), ("mv_network",), ("immersiveengineering:component_electronic", 4), 6, "pta_resource"),
    n("breaker", "Выключатель", "V · ЭЛЕКТРОСЕТЬ", "Отключай участок сети вручную перед обслуживанием.", 1495, 930, "circle", 1.0, ("immersiveengineering:breaker_switch", 2), ("mv_capacitor",), ("minecraft:lever", 4), 5, "pta_auto"),
    n("redstone_breaker", "Редстоун-выключатель", "V · ЭЛЕКТРОСЕТЬ", "Автоматически управляй подачей энергии сигналом.", 1545, 850, "circle", 1.0, ("immersiveengineering:redstone_breaker", 2), ("breaker",), ("immersiveengineering:wirecoil_redstone", 2), 6, "pta_auto"),
    n("current_transformer", "Трансформатор тока", "V · ЭЛЕКТРОСЕТЬ", "Отслеживай потребление и включай резервную генерацию.", 1580, 760, "circle", 1.05, ("immersiveengineering:current_transformer", 1), ("redstone_breaker",), ("immersiveengineering:voltmeter", 1), 7, "pta_auto"),

    # Processing branch.
    n("conveyor", "Конвейер", "VI · МАШИНЫ", "Перемещай предметы по безопасным маршрутам между машинами.", 1270, 430, "hexagon", 1.0, ("immersiveengineering:conveyor_basic", 16), ("metal_press",), ("immersiveengineering:conveyor_vertical", 4), 4, "pta_auto"),
    n("chute", "Жёлоб", "VI · МАШИНЫ", "Спускай предметы между этажами без сложных труб.", 1325, 345, "hexagon", 1.0, ("immersiveengineering:chute_steel", 8), ("conveyor",), ("immersiveengineering:conveyor_dropper", 4), 4, "pta_auto"),
    n("redstone_conveyor", "Управляемый конвейер", "VI · МАШИНЫ", "Включай и останавливай секции сигналом редстоуна.", 1385, 275, "hexagon", 1.0, ("immersiveengineering:conveyor_redstone", 8), ("chute",), ("minecraft:redstone", 16), 5, "pta_auto"),
    n("plate_mold", "Форма пластины", "VI · МАШИНЫ", "Выбери форму пресса и сократи расход металла.", 1450, 215, "hexagon", 1.0, ("immersiveengineering:mold_plate", 1), ("redstone_conveyor",), ("immersiveengineering:plate_steel", 8), 5, "pta_auto"),
    n("rod_wire_molds", "Формы стержня и провода", "VI · МАШИНЫ", "Автоматизируй стандартные полуфабрикаты для других модов.", 1515, 175, "hexagon", 1.0, (("immersiveengineering:mold_rod", 1), ("immersiveengineering:mold_wire", 1)), ("plate_mold",), ("immersiveengineering:wire_copper", 16), 5, "pta_auto"),
    n("gear_mold", "Форма шестерни", "VI · МАШИНЫ", "Создавай компоненты механизмов серийно.", 1580, 155, "hexagon", 1.0, ("immersiveengineering:mold_gear", 1), ("rod_wire_molds",), ("immersiveengineering:component_steel", 4), 6, "pta_auto"),
    n("sorter", "Сортировщик", "VI · МАШИНЫ", "Разделяй продукцию по цветным каналам и фильтрам.", 1645, 175, "hexagon", 1.0, ("immersiveengineering:sorter", 1), ("gear_mold",), ("immersiveengineering:crate", 2), 6, "pta_auto"),
    n("silo", "Силос", "VI · МАШИНЫ", "Храни один массовый ресурс и контролируй его запас.", 1710, 215, "hexagon", 1.0, ("immersiveengineering:silo", 1), ("sorter",), ("immersiveengineering:storage_steel", 1), 6, "pta_auto"),
    n("tank", "Резервуар", "VI · МАШИНЫ", "Храни большие объёмы промышленных жидкостей.", 1770, 275, "hexagon", 1.0, ("immersiveengineering:tank", 1), ("silo",), ("immersiveengineering:fluid_pipe", 8), 6, "pta_auto"),
    n("bottling", "Разливочная машина", "VI · МАШИНЫ", "Наполняй контейнеры и обрабатывай предметы жидкостями.", 1815, 345, "hexagon", 1.0, ("immersiveengineering:bottling_machine", 1), ("tank",), ("minecraft:bucket", 8), 7, "pta_auto"),
    n("auto_line", "Автоматическая линия", "VI · МАШИНЫ", "Соедини пресс, дробитель, сортировку и склады без ручного переноса.", 1835, 430, "hexagon", 1.1, (("immersiveengineering:conveyor_basic", 32), ("immersiveengineering:sorter", 2), ("immersiveengineering:reinforced_crate", 4)), ("bottling",), ("immersiveengineering:component_electronic_adv", 2), 9, "pta_auto"),

    # Fuel branch.
    n("squeezer", "Выжимной пресс", "VII · ТОПЛИВО", "Получай растительное масло из семян и перерабатывай биомассу.", 1570, 760, "square", 1.0, ("immersiveengineering:squeezer", 1), ("fluid_network",), ("immersiveengineering:plantoil_bucket", 1), 6, "pta_auto"),
    n("plant_oil", "Растительное масло", "VII · ТОПЛИВО", "Стабилизируй ферму сырья и буфер жидкости.", 1625, 850, "square", 1.0, ("immersiveengineering:plantoil_bucket", 8), ("squeezer",), ("immersiveengineering:tank", 1), 6, "pta_auto"),
    n("fermenter", "Ферментер", "VII · ТОПЛИВО", "Превращай сахарный тростник и растения в этанол.", 1690, 925, "square", 1.0, ("immersiveengineering:fermenter", 1), ("plant_oil",), ("immersiveengineering:ethanol_bucket", 1), 6, "pta_auto"),
    n("ethanol", "Этанол", "VII · ТОПЛИВО", "Сбалансируй два потока сырья для непрерывного производства.", 1760, 965, "square", 1.0, ("immersiveengineering:ethanol_bucket", 8), ("fermenter",), ("immersiveengineering:fluid_pipe", 8), 7, "pta_auto"),
    n("mixer", "Смеситель", "VII · ТОПЛИВО", "Освой смешивание жидкостей и добавок в промышленном чане.", 1830, 940, "square", 1.0, ("immersiveengineering:mixer", 1), ("ethanol",), ("immersiveengineering:component_electronic", 4), 7, "pta_auto"),
    n("fuel_pipes", "Трубопровод", "VII · ТОПЛИВО", "Настрой входы и выходы нефтеперерабатывающего завода.", 1895, 880, "square", 1.0, (("immersiveengineering:fluid_pipe", 24), ("immersiveengineering:pipe_valve", 4)), ("mixer",), ("immersiveengineering:fluid_sorter", 1), 7, "pta_auto"),
    n("fuel_storage", "Хранилище топлива", "VII · ТОПЛИВО", "Запаси биодизель отдельно от промежуточных жидкостей.", 1940, 810, "square", 1.0, (("immersiveengineering:biodiesel_bucket", 16), ("immersiveengineering:tank", 2)), ("fuel_pipes",), ("immersiveengineering:high_power_biodiesel_bucket", 2), 8, "pta_auto"),
    n("generator_load", "Нагрузка генератора", "VII · ТОПЛИВО", "Испытай топливную линию под постоянной промышленной нагрузкой.", 1955, 745, "square", 1.1, (("immersiveengineering:capacitor_hv", 1), ("immersiveengineering:connector_hv", 4)), ("fuel_storage",), ("immersiveengineering:wirecoil_steel", 4), 9, "pta_auto"),

    # Heavy industry branch.
    n("sample_drill", "Буровая установка", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Возьми пробу грунта и найди месторождение минералов.", 1850, 430, "circle", 1.0, ("immersiveengineering:sample_drill", 1), ("biodiesel",), ("immersiveengineering:survey_tools", 1), 7, "pta_danger"),
    n("core_sample", "Керновая проба", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Научись читать состав, ёмкость и истощение месторождения.", 1915, 335, "circle", 1.0, ("immersiveengineering:coresample", 1), ("sample_drill",), ("immersiveengineering:component_steel", 4), 7, "pta_danger"),
    n("heavy_structure", "Стальная конструкция", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Подготовь леса, тяжёлые блоки и инженерные компоненты.", 1985, 255, "circle", 1.0, (("immersiveengineering:steel_scaffolding_standard", 32), ("immersiveengineering:component_steel", 16)), ("core_sample",), ("immersiveengineering:plate_steel", 16), 8, "pta_danger"),
    n("bucket_wheel", "Роторное колесо", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Собери Bucket Wheel и проверь направление вращения.", 2060, 195, "circle", 1.0, ("immersiveengineering:bucket_wheel", 1), ("heavy_structure",), ("immersiveengineering:ingot_steel", 16), 9, "pta_danger"),
    n("excavator", "Экскаватор", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Добывай ресурсы из найденной жилы за счёт большого расхода энергии.", 2140, 175, "circle", 1.1, ("immersiveengineering:excavator", 1), ("bucket_wheel",), ("immersiveengineering:capacitor_hv", 1), 11, "pta_danger"),
    n("lightning_rod", "Грозовой стержень", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Защити комплекс и используй грозу как редкий источник энергии.", 2210, 245, "circle", 1.0, ("immersiveengineering:lightning_rod", 1), ("excavator",), ("immersiveengineering:capacitor_hv", 1), 10, "pta_danger"),
    n("arc_recycling", "Переработка в дуге", "VIII · ТЯЖЁЛАЯ ИНДУСТРИЯ", "Возвращай металл из старого оборудования через Arc Furnace.", 2260, 400, "circle", 1.1, (("immersiveengineering:ingot_steel", 128), ("immersiveengineering:slag", 32)), ("lightning_rod",), ("immersiveengineering:graphite_electrode", 1), 12, "pta_danger"),

    # Equipment branch.
    n("revolver", "Револьвер", "IX · ИНТЕГРАЦИЯ", "Собери модульное оружие и изучи разные типы патронов.", 1995, 760, "diamond", 1.0, ("immersiveengineering:revolver", 1), ("diesel_generator",), ("immersiveengineering:bullet_casull", 16), 7, "pta_resource"),
    n("speedloader", "Быстрая перезарядка", "IX · ИНТЕГРАЦИЯ", "Используй Speedloader и организуй производство боеприпасов.", 2050, 845, "diamond", 1.0, (("immersiveengineering:speedloader", 1), ("immersiveengineering:bullet_casull", 32)), ("revolver",), ("immersiveengineering:bullet_armor_piercing", 8), 8, "pta_resource"),
    n("drill", "Шахтёрский бур", "IX · ИНТЕГРАЦИЯ", "Создай электрический бур и настрой его улучшения.", 2110, 920, "diamond", 1.0, (("immersiveengineering:drill", 1), ("immersiveengineering:drillhead_steel", 1)), ("speedloader",), ("immersiveengineering:toolupgrade_drill_capacity", 1), 9, "pta_resource"),
    n("chemthrower", "Химический распылитель", "IX · ИНТЕГРАЦИЯ", "Применяй жидкости как инструмент и оружие с понятными ограничениями.", 2170, 950, "diamond", 1.0, ("immersiveengineering:chemthrower", 1), ("drill",), ("immersiveengineering:toolupgrade_chemthrower_multitank", 1), 9, "pta_resource"),
    n("railgun", "Рельсотрон", "IX · ИНТЕГРАЦИЯ", "Освой мощное электрическое оружие и расход энергии.", 2230, 900, "diamond", 1.0, ("immersiveengineering:railgun", 1), ("chemthrower",), ("immersiveengineering:toolupgrade_railgun_capacitors", 1), 10, "pta_resource"),
    n("turret", "Автоматическая турель", "IX · ИНТЕГРАЦИЯ", "Защити промышленную площадку и настрой безопасный список целей.", 2275, 780, "diamond", 1.1, (("immersiveengineering:turret_gun", 1), ("immersiveengineering:turret_chem", 1)), ("railgun",), ("immersiveengineering:component_electronic_adv", 4), 11, "pta_resource"),
]
