"""Quest data for the five expansion chapters added in book version 1.12.0.

The visible stage titles mirror the approved interactive mock-up.  Item pools
contain registry IDs verified against the exact JAR files shipped by the pack.
"""

CHAPTERS = {
    "minecolonies": {
        "title": "MineColonies: город на острове", "file": "minecolonies",
        "icon": "minecolonies:blockhuttownhall", "target_count": 110,
        "append_control": False,
        "stage_parents": [(), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (1, 2, 3, 4, 5, 6, 7), (8,), (9,)],
        "stages": [
            ("I · ОСНОВАНИЕ", "Первое поселение", ["Supply Camp", "Build Tool", "Ратуша", "Первый житель", "Дом жителя", "Таверна", "Безопасная территория", "План улиц", "Первый уровень", "Колония основана"]),
            ("II · СТРОЙКА", "Строительный квартал", ["Хижина строителя", "Склад материалов", "Очередь строительства", "Улучшение строителя", "Два строителя", "Инструменты работника", "Доставка блоков", "Ремонт здания", "Стиль колонии", "Квартал строителей"]),
            ("III · РЕСУРСЫ", "Промышленный район", ["Лесоруб", "Шахтёр", "Каменщик", "Плавильня", "Кузнец", "Дробильщик", "Стеклодув", "Лесопилка", "Каменоломня", "Ресурсный контур"]),
            ("IV · ЕДА", "Фермерский пояс", ["Фермер", "Поле", "Пастух", "Коровник", "Курятник", "Рыбак", "Пекарь", "Повар", "Кухня", "Запас еды"]),
            ("V · РЕМЁСЛА", "Гильдии мастеров", ["Механик", "Красильщик", "Цветочник", "Компостер", "Бетонщик", "Алхимик", "Зачарователь", "Флетчер", "Мистическое место", "Гильдейский район"]),
            ("VI · ЛОГИСТИКА", "Складской узел", ["Склад", "Курьер", "Стойки", "Маршруты", "Минимальный запас", "Приоритеты", "Почта", "Ресурсный свиток", "Аварийный резерв", "Стабильная логистика"]),
            ("VII · ЗНАНИЯ", "Академический район", ["Университет", "Исследование", "Библиотека", "Школа", "Обучение жителей", "Скорость работы", "Здоровье жителей", "Новые профессии", "Полное древо", "Центр знаний"]),
            ("VIII · ОБОРОНА", "Крепость", ["Башня стражи", "Казармы", "Башня казарм", "Лучник", "Рыцарь", "Ворота", "Патруль", "Точка сбора", "Ночной рейд", "Защищённая колония"]),
            ("IX · УПРАВЛЕНИЕ", "Городской совет", ["Карта колонии", "Права доступа", "Наём жителей", "Счастье", "Жильё", "Здоровье", "Рабочие места", "Баланс ресурсов", "План расширения", "Совет колонии"]),
            ("X · ТОРГОВЛЯ", "Экономика города", ["Торговая почта", "Заказ ресурсов", "Экспорт еды", "Экспорт ремесла", "Импорт редкостей", "Контракт", "Караван", "Резерв валюты", "Торговый район", "Городская экономика"]),
            ("XI · МЕТРОПОЛИЯ", "Столица островов", ["Здания V уровня", "Все профессии", "Полный склад", "Автодоставка", "Сильный гарнизон", "Высшее образование", "Стабильная еда", "Производственный план", "Монумент города", "Мэр мегаполиса"]),
        ],
        "centers": [(52, 25), (5, 6), (5, 23), (5, 42), (27, 5), (27, 43), (55, 5), (55, 43), (82, 12), (82, 36), (108, 25)],
        "patterns": ["doubleRing", "grid", "mirror", "ring", "diamond", "grid", "star", "containment", "crescentD", "fanL", "doubleRing"],
    },
    "oritech": {
        "title": "Oritech: орбитальная промышленность", "file": "oritech",
        "icon": "oritech:atomic_forge_block", "target_count": 90, "append_control": False,
        "stages": [
            ("I · СЫРЬЁ", "Новые металлы", ["Никелевая руда", "Платиновая руда", "Урановая руда", "Угольная пыль", "Стальная пыль", "Электрум", "Fluxite", "Кремний", "Машинная рама", "Материальный запас"]),
            ("II · ЭНЕРГИЯ", "Первый энергоконтур", ["Базовый генератор", "Топливный генератор", "Лавовый генератор", "Биогенератор", "Солнечная панель", "Батарея", "Энергетическая труба", "Опора сети", "Резерв энергии", "Стабильная сеть"]),
            ("III · ОБРАБОТКА", "Машинный цех", ["Электропечь", "Pulverizer", "Foundry", "Assembler", "Centrifuge", "Refinery", "Shrinker", "Fragment Forge", "Параллельная линия", "Цех обработки"]),
            ("IV · ЛОГИСТИКА", "Потоки фабрики", ["Предметная труба", "Жидкостная труба", "Фильтр предметов", "Усилитель трубы", "Хранилище", "Бак", "Насос", "Placer", "Дрон-порт", "Автологистика"]),
            ("V · ЛАЗЕРЫ", "Технологии луча", ["Laser Arm", "Portable Laser", "Зарядная станция", "Магнитная катушка", "Enderic Lens", "Particle Collector", "Destroyer", "Atomic Forge", "Защита лазера", "Лазерный комплекс"]),
            ("VI · ГЛУБИНА", "Добыча из узлов", ["Resource Node", "Deep Drill", "Quarry Addon", "Silk Touch Addon", "Yield Addon", "Speed Addon", "Processing Addon", "Буфер руды", "Автопереработка", "Глубинный комплекс"]),
            ("VII · РЕАКТОР", "Ядерная установка", ["Урановая пыль", "Топливная гранула", "Стенка реактора", "Топливный порт", "Стержень", "Отражатель", "Конденсатор", "Энергопорт", "Аварийная остановка", "Стабильный реактор"]),
            ("VIII · КВАНТ", "Ускоритель частиц", ["Accelerator Controller", "Accelerator Ring", "Accelerator Motor", "Accelerator Sensor", "Heisenberg Compensator", "Overcharged Crystal", "Adamant", "Black Hole", "Контроль поля", "Квантовый контур"]),
            ("IX · ОРБИТА", "Космический завод", ["Jetpack", "Exo Armor", "Ion Thruster", "Superconductor", "Ultimate Addon", "Quantum Battery", "Прометий", "Орбитальный модуль", "Полная автоматика", "Орбитальная фабрика"]),
        ],
        "centers": [(48, 24), (52, 9), (70, 5), (88, 16), (91, 34), (73, 44), (48, 44), (26, 35), (25, 12)],
        "patterns": ["ring", "diamond", "grid", "mirror", "hex", "fanL", "star", "containment", "doubleRing"],
    },
    "silentgear": {
        "title": "Silent Gear: кузнечное древо", "file": "silentgear",
        "icon": "silentgear:blueprint_book", "target_count": 90, "append_control": False,
        "stage_parents": [(), (0,), (0,), (0,), (0,), (1, 2, 3, 4), (5,), (5,), (5,)],
        "stages": [
            ("I · ЧЕРТЕЖИ", "Язык мастера", ["Guide Book", "Blueprint Paper", "Blueprint Package", "Tool Blueprint", "Armor Blueprint", "Part Blueprint", "Material Book", "Пробная рукоять", "Пробное лезвие", "Первый чертёж"]),
            ("II · МАТЕРИАЛЫ", "Свойства сырья", ["Дерево", "Камень", "Железо", "Золото", "Алмаз", "Незерит", "Crimson Iron", "Azure Silver", "Сравнение свойств", "Библиотека сырья"]),
            ("III · ДЕТАЛИ", "Модульная сборка", ["Rod", "Grip", "Binding", "Tip", "Coating", "Lining", "Cord", "Compound Part", "Совместимость деталей", "Полный набор частей"]),
            ("IV · КАЧЕСТВО", "Оценка и ремонт", ["Material Grader", "Grade E", "Grade D", "Grade C", "Grade B", "Grade A", "Grade S", "Repair Kit", "Ремонт без потери", "Идеальная заготовка"]),
            ("V · КУЗНИЦА", "Сборочный узел", ["Gear Smithing Table", "Tool Rod", "Pickaxe Head", "Sword Blade", "Armor Plates", "Сборка инструмента", "Сборка оружия", "Сборка брони", "Разбор сборки", "Мастерская Silent Gear"]),
            ("VI · УЛУЧШЕНИЯ", "Тонкая настройка", ["Upgrade Base", "Tip Upgrade", "Coating Upgrade", "Grip Upgrade", "Lining Upgrade", "Magnetic Upgrade", "Red Card Upgrade", "Road Maker Upgrade", "Сбалансированный модуль", "Набор улучшений"]),
            ("VII · ШАХТЁР", "Комплект добычи", ["Кирка", "Молот", "Excavator", "Prospector Hammer", "Paxel", "Repair Kit", "Скорость добычи", "Долговечность", "Полевой тест", "Мастер рудника"]),
            ("VIII · ВОИН", "Комплект боя", ["Меч", "Кинжал", "Катана", "Лук", "Щит", "Броня", "Урон", "Скорость атаки", "Испытание босса", "Мастер оружия"]),
            ("IX · ИНЖЕНЕР", "Комплект производства", ["Alloy Forge", "Crimson Steel", "Azure Electrum", "Refabricator", "Recrystallizer", "Salvager", "Склад чертежей", "Три специализации", "Выставка комплектов", "Легендарный мастер"]),
        ],
        "centers": [(52, 43), (25, 33), (42, 28), (62, 28), (80, 33), (52, 18), (25, 5), (52, 4), (80, 5)],
        "patterns": ["fanR", "ring", "diamond", "mirror", "star", "doubleRing", "grid", "containment", "grid"],
    },
    "cobbleplus": {
        "title": "Cobblemon+: карта живого региона", "file": "cobbleplus",
        "icon": "cobblemonraiddens:raid_pouch", "target_count": 120, "append_control": False,
        "stage_parents": [(), (0,), (0,), (1,), (2,), (2,), (3,), (4, 5), (6,), (7, 8), (9,), (10,)],
        "stages": [
            ("I · ПОЛЕ", "Дневник натуралиста", ["Cobbledex", "Первые 10 видов", "Биомы", "Время суток", "Погода", "Формы", "Редкая окраска", "Фото наблюдения", "Карта встреч", "Натуралист региона"]),
            ("II · ПИТОМНИК", "Cobbreeding", ["Pasture", "Пара родителей", "Яйцо", "Совместимость", "Наследование", "Destiny Knot", "Способность", "Характер", "Цепочка поколений", "Идеальный питомник"]),
            ("III · ТАКТИКА", "Командная школа", ["Команда типов", "Роли покемонов", "Статусные ходы", "Предметы боя", "TM-система", "Смена темпа", "Контртип", "План на босса", "Тренировочный матч", "Командная синергия"]),
            ("IV · РЕЙДЫ", "Raid Dens", ["Поиск логова", "Raid Pouch", "Подготовка группы", "Фаза щита", "Слабость босса", "Поддержка команды", "Редкая награда", "Высокий тир", "Серия рейдов", "Хозяин логов"]),
            ("V · БАШНЯ", "Battle Tower", ["Вход в башню", "Правила состава", "Первый этаж", "Серия побед", "Элитный этаж", "Ограниченный бой", "Награда башни", "Финальный этаж", "Повторный сезон", "Чемпион башни"]),
            ("VI · МЕГА", "Mega Showdown", ["Mega Stone", "Key Stone", "Mega Evolution", "Red Orb", "Blue Orb", "Soul Dew", "Особая форма", "Тест формы", "Команда мегаволюции", "Мастер трансформаций"]),
            ("VII · МОНУМЕНТЫ", "Legendary Monuments", ["След легенды", "Ключ монумента", "Regi-замок", "Озёрные стражи", "Azure Flute", "Следы мечей", "Музыкальный алтарь", "Печать Eternatus", "Ритуал призыва", "Хранитель монументов"]),
            ("VIII · ЭКСПЕДИЦИИ", "Коллекции легенд", ["Легендарные птицы", "Галарские птицы", "Легендарные звери", "Мифические покемоны", "Ultra Beasts", "Редкие условия", "Командная охота", "Безопасный захват", "Архив легенд", "Коллекционер региона"]),
            ("IX · ИНДУСТРИЯ", "Cobblemon Industries", ["Цветная жидкость", "Обработка компонентов", "Линия покеболов", "Лекарственная линия", "Машинный корпус", "Энергия производства", "Сортировка продукции", "Контроль качества", "Полный цикл", "Покемонская фабрика"]),
            ("X · MANUFACTORY", "Инженерия покеболов", ["Iron Ball Base", "Ball Lid", "Incomplete Ball", "Автоподача", "Серийная сборка", "Редкий покебол", "Склад компонентов", "Заказ через AE2", "Производственный тест", "Manufactory-комплекс"]),
            ("XI · ДАНЖИ", "Региональные испытания", ["Радикальный зал", "Тренерский данж", "Командный босс", "Экспедиционный набор", "Три победы подряд", "Редкий трофей", "Маршрут без смерти", "Повторный забег", "Главная арена", "Покоритель данжей"]),
            ("XII · ЛИГА", "Чемпион живого региона", ["Полный состав", "Команда для рейда", "Команда для башни", "Команда для данжа", "Легендарный партнёр", "Своя фабрика", "Свой питомник", "Региональный покедекс", "Финальный турнир", "Чемпион региона"]),
        ],
        "centers": [(0, 24), (18, 8), (18, 40), (38, 5), (42, 24), (38, 43), (61, 8), (66, 38), (86, 5), (90, 24), (86, 43), (112, 24)],
        "patterns": ["fanR", "ring", "crescentD", "star", "diamond", "mirror", "doubleRing", "containment", "grid", "hex", "fanL", "doubleRing"],
    },
    "worldbosses": {
        "title": "Миры и боссы: атлас экспедиций", "file": "worldbosses",
        "icon": "bosses_of_mass_destruction:soul_star", "target_count": 110, "append_control": False,
        "stage_parents": [(), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (1, 2, 3, 4, 5, 6, 7, 8), (9,)],
        "stages": [
            ("I · ЛАГЕРЬ", "Подготовка экспедиции", ["Рюкзак", "Waystone", "Карта", "Запас еды", "Зелья", "Ремонт", "Точка эвакуации", "Командные роли", "Сундук трофеев", "Лицензия охотника"]),
            ("II · ДИКАЯ ЗЕМЛЯ", "Mowzie’s Mobs", ["След редкого моба", "Грот Ферроса", "Frostmaw", "Barakoa", "Naga", "Подготовка арены", "Изучение атак", "Победа без смерти", "Редкий трофей", "Охотник Mowzie’s"]),
            ("III · ХАОС", "Born in Chaos", ["Заражённый биом", "Ночная волна", "Элитный монстр", "Проклятое оружие", "Укрытие", "Очищение зоны", "Боевой маршрут", "Штурм гнезда", "Трофей хаоса", "Победитель хаоса"]),
            ("IV · МУТАЦИИ", "Mutant Monsters", ["Chemical X", "Mutant Zombie", "Mutant Skeleton", "Mutant Creeper", "Mutant Enderman", "Контратаки", "Безопасная дистанция", "Полная серия", "Набор трофеев", "Истребитель мутантов"]),
            ("V · МОГИЛЫ", "Bosses of Mass Destruction", ["Soul Star", "Night Lich", "Obsidilith", "Nether Gauntlet", "Void Blossom", "Фазы босса", "Командный бой", "Редкая реликвия", "Повторная охота", "Чемпион BOMD"]),
            ("VI · ФАБРИКА", "Block Factory’s Bosses", ["Ancient Trial Key", "Арена пиратов", "Kraken", "Yeti", "Sandworm", "Infernal Dragon", "Underworld Knight", "Технологический трофей", "Скоростной забег", "Покоритель фабрики"]),
            ("VII · ЗВЁЗДНЫЙ МИР", "Eternal Starlight", ["Портал Starlight", "Первый биом", "Редкий ресурс", "Звёздная структура", "Местная угроза", "Навигация мира", "Главный страж", "Артефакт света", "Безопасный маршрут", "Исследователь Starlight"]),
            ("VIII · ЗАЛЫ", "Radical Gyms", ["Карта залов", "Первый лидер", "Типовая команда", "Головоломка зала", "Средний лидер", "Высший лидер", "Серия значков", "Команда без легенд", "Финальный значок", "Мастер залов"]),
            ("IX · СТРУКТУРЫ", "Большой маршрут", ["Towns and Towers", "YUNG-структура", "Редкая башня", "Подземный комплекс", "Секретная комната", "Карта лута", "Маршрут Waystones", "Экспедиция без смерти", "Архив структур", "Великий картограф"]),
            ("X · КЛЮЧИ", "Совет охотников", ["Трофей дикой земли", "Трофей хаоса", "Трофей мутантов", "Трофей могильника", "Трофей фабрики", "Трофей Starlight", "Значки залов", "Карта структур", "Семь ключей", "Совет охотников"]),
            ("XI · ФИНАЛ", "Охота века", ["Выбор снаряжения", "Команда игроков", "Команда покемонов", "Цепочка арен", "Ограничение смертей", "Смена тактики", "Финальная фаза", "Общий трофей", "Монумент охоты", "Легенда экспедиций"]),
        ],
        "centers": [(52, 24), (5, 5), (5, 24), (5, 43), (27, 5), (27, 43), (73, 5), (73, 43), (96, 10), (96, 38), (115, 24)],
        "patterns": ["doubleRing", "grid", "star", "mirror", "containment", "hex", "fanR", "crescentD", "ring", "diamond", "doubleRing"],
    },
}


ITEM_POOLS = {
    "minecolonies": [
        "minecolonies:supplycampdeployer", "minecolonies:blockhuttownhall", "minecolonies:blockhutcitizen", "minecolonies:blockhuttavern",
        "minecolonies:blockhutbuilder", "minecolonies:build_goggles", "minecolonies:clipboard", "minecolonies:blockconstructiontape",
        "minecolonies:blockhutlumberjack", "minecolonies:blockhutminer", "minecolonies:blockhutstonemason", "minecolonies:blockhutsmeltery",
        "minecolonies:blockhutblacksmith", "minecolonies:blockhutcrusher", "minecolonies:blockhutglassblower", "minecolonies:blockhutsawmill",
        "minecolonies:blockhutfarmer", "minecolonies:blockhutfield", "minecolonies:blockhutshepherd", "minecolonies:blockhutcowboy",
        "minecolonies:blockhutchickenherder", "minecolonies:blockhutfisherman", "minecolonies:blockhutbaker", "minecolonies:blockhutcook",
        "minecolonies:blockhutwarehouse", "minecolonies:blockhutdeliveryman", "minecolonies:blockminecoloniesrack", "minecolonies:resourcescroll",
        "minecolonies:blockhutuniversity", "minecolonies:blockhutlibrary", "minecolonies:blockhutschool", "minecolonies:blockhutguardtower",
        "minecolonies:blockhutbarracks", "minecolonies:blockhutgatehouse", "minecolonies:banner_rally_guards", "minecolonies:colonymap",
        "minecolonies:colony_banner", "minecolonies:blockpostbox", "minecolonies:questlog", "minecolonies:ancienttome",
    ],
    "oritech": [
        "oritech:raw_nickel", "oritech:raw_platinum", "oritech:raw_uranium", "oritech:steel_ingot", "oritech:electrum_ingot",
        "oritech:fluxite", "oritech:silicon", "oritech:machine_frame_block", "oritech:basic_generator_block", "oritech:fuel_generator_block",
        "oritech:bio_generator_block", "oritech:big_solar_panel_block", "oritech:basic_battery", "oritech:advanced_battery", "oritech:energy_pipe",
        "oritech:powered_furnace_block", "oritech:pulverizer_block", "oritech:foundry_block", "oritech:assembler_block", "oritech:centrifuge_block",
        "oritech:refinery_block", "oritech:shrinker_block", "oritech:fragment_forge_block", "oritech:item_pipe", "oritech:fluid_pipe",
        "oritech:item_filter_block", "oritech:pipe_booster_block", "oritech:small_storage_block", "oritech:small_tank_block", "oritech:pump_block",
        "oritech:laser_arm_block", "oritech:portable_laser", "oritech:charger_block", "oritech:enderic_lens", "oritech:particle_collector_block",
        "oritech:deep_drill_block", "oritech:quarry_addon", "oritech:machine_silk_touch_addon", "oritech:machine_yield_addon", "oritech:machine_speed_addon",
        "oritech:reactor_controller", "oritech:reactor_wall", "oritech:reactor_fuel_port", "oritech:reactor_rod", "oritech:reactor_energy_port",
        "oritech:accelerator_controller", "oritech:accelerator_ring", "oritech:accelerator_motor", "oritech:accelerator_sensor", "oritech:heisenberg_compensator",
        "oritech:overcharged_crystal", "oritech:adamant_ingot", "oritech:black_hole_block", "oritech:exo_jetpack", "oritech:prometheum_ingot",
    ],
    "silentgear": [
        "silentgear:guide_book", "silentgear:blueprint_paper", "silentgear:blueprint_package", "silentgear:blueprint_book", "silentgear:material_book",
        "silentgear:rod_blueprint", "silentgear:grip_blueprint", "silentgear:binding_blueprint", "silentgear:coating_blueprint", "silentgear:lining_blueprint",
        "silentgear:rod", "silentgear:grip", "silentgear:binding", "silentgear:coating", "silentgear:lining", "silentgear:cord",
        "silentgear:material_grader", "silentgear:crude_repair_kit", "silentgear:crimson_repair_kit", "silentgear:azure_repair_kit",
        "silentgear:gear_smithing_table", "silentgear:pickaxe_head", "silentgear:sword_blade", "silentgear:helmet_plates", "silentgear:chestplate_plates",
        "silentgear:advanced_upgrade_base", "silentgear:magnetic_upgrade", "silentgear:red_card_upgrade", "silentgear:road_maker_upgrade", "silentgear:mod_kit",
        "silentgear:pickaxe", "silentgear:hammer", "silentgear:excavator", "silentgear:prospector_hammer", "silentgear:paxel",
        "silentgear:sword", "silentgear:dagger", "silentgear:katana", "silentgear:bow", "silentgear:shield", "silentgear:helmet", "silentgear:chestplate",
        "silentgear:alloy_forge", "silentgear:crimson_steel_ingot", "silentgear:azure_electrum_ingot", "silentgear:refabricator", "silentgear:recrystallizer", "silentgear:salvager",
    ],
    "cobbleplus": [
        "cobbledex:cobbledex_item", "cobblemon:pasture", "cobblemon:destiny_knot", "cobbreeding:normal_pokemon_egg",
        "cobblemon:focus_sash", "cobblemon:rare_candy", "cobblemonraiddens:raid_pouch", "cobblemonraiddens:raid_shard",
        "cobblemonraiddens:catching_charm", "cobblemon_battle_tower:holo_battle_tower", "mega_showdown:mega_stone",
        "mega_showdown:red_orb", "mega_showdown:blue_orb", "mega_showdown:soul_dew", "mega_showdown:deoxys_meteorite",
        "legendarymonuments:registeel_lock", "legendarymonuments:azure_flute", "legendarymonuments:eternatus_cocoon",
        "legendarymonuments:dragon_golem_key", "legendarymonuments:galar_particle", "cobblemon_industries:red_fluid_bucket",
        "cobblemon_industries:blue_fluid_bucket", "cobblemon_manufactory:iron_ball_base", "cobblemon_manufactory:red_ball_lid",
        "cobblemon_manufactory:great_ball_lid", "cobblemon_manufactory:ultra_ball_lid", "cobblemon_manufactory:incomplete_poke_ball",
        "cobblemon_manufactory:incomplete_great_ball", "cobblemon_manufactory:incomplete_ultra_ball", "cobblemon:master_ball",
    ],
    "worldbosses": [
        "minecraft:filled_map", "minecraft:compass", "minecraft:golden_apple", "minecraft:shield", "minecraft:ender_chest",
        "mowziesmobs:wrought_axe", "mowziesmobs:wrought_helmet", "mowziesmobs:ice_crystal", "mowziesmobs:sol_visage",
        "mowziesmobs:naga_fang", "mowziesmobs:earthrend_gauntlet", "born_in_chaos_v1:evilometer", "born_in_chaos_v1:dark_metal_ingot",
        "born_in_chaos_v1:darkwarblade", "born_in_chaos_v1:death_totem", "born_in_chaos_v1:bone_heart",
        "mutantmonsters:creeper_shard", "mutantmonsters:creeper_shard", "mutantmonsters:endersoul_hand", "mutantmonsters:hulk_hammer",
        "mutantmonsters:mutant_skeleton_skull", "bosses_of_mass_destruction:soul_star", "bosses_of_mass_destruction:obsidian_heart",
        "bosses_of_mass_destruction:earthdive_spear", "bosses_of_mass_destruction:ancient_anima", "bosses_of_mass_destruction:void_lily",
        "block_factorys_bosses:ancient_trial_key", "block_factorys_bosses:kraken_tooth", "block_factorys_bosses:kraken_trident",
        "block_factorys_bosses:ice_gauntlet", "block_factorys_bosses:dragon_bone", "block_factorys_bosses:underworld_arena_key",
        "eternal_starlight:book", "eternal_starlight:blue_starlight_crystal_shard", "eternal_starlight:aethersent_ingot",
        "minecraft:nether_star", "minecraft:dragon_egg", "minecraft:beacon", "minecraft:totem_of_undying",
    ],
}
